version: "3.7"
services:
  challenge-service:
    build:
      context: .
    image: maven/builder:0.0.1
    container_name: challenge-service
    ports:
      - "8090:8090"
    environment:
      POSTGRES_USER: challenge_db
      POSTGRES_PASSWORD: challenge_db
      POSTGRES_DB: challenge_db
    volumes:
      - "./src:/build/src"
      - "./target:/build/target:cached"
    command: "mvn spring-boot:run"
    depends_on:
      - challenge_db
  challenge_db:
    container_name: challenge_db
    restart: always
    image: "postgres:12"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: challenge_db
      POSTGRES_PASSWORD: challenge_db
      POSTGRES_DB: challenge_db
    volumes:
      - challenge-service_data:/var/lib/postgresql/data
volumes:
  challenge-service_data: { }