version: "3.8"
services:
  challenge-service:
    build:
      context: .
    container_name: challenge-service
    ports:
      - "8090:8090"
    environment:
      POSTGRES_USER: ${CHALLENGE_DB_USER}
      POSTGRES_PASSWORD: ${CHALLENGE_DB_PASSWORD}
      POSTGRES_DB: ${CHALLENGE_DB}
    volumes:
      - "./src:/build/src"
      - "./target:/build/target:cached"
    command: "mvn spring-boot:run"
    depends_on:
      - challenge_db
  challenge_db:
    container_name: challenge_db
    restart: always
    image: "postgres:12"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${CHALLENGE_DB_USER}
      POSTGRES_PASSWORD: ${CHALLENGE_DB_PASSWORD}
      POSTGRES_DB: ${CHALLENGE_DB}
    volumes:
      - challenge-service_data:/var/lib/postgresql/data
volumes:
  challenge-service_data: { }